dirichlet:
  alpha: 0.5  # alpha for dirichlet distribution

client:
  num_clients: 5  # number of clients
  epochs: 5  # number of epochs
  lr: 0.01  # learning rate
  proximal_coff: 0.35

global:
  rounds: 5  # number of rounds
  random_select_ratio: 0.33 # ratio of random selection from the number of clients

dataset:
  distribution: 'dirichlet'  # 'iid' or 'dirichlet'
  name: 'mnist'  # 'mnist' or 'cifar10'
  path: 'dataset/'  # path to dataset
  num_classes: 10  # number of classes in dataset
  batch_size: 32  # batch size

train:
  momentum: 0.9  # momentum for aggregation
  aggregator_method: 'fedavgM' # 'fedavg' or 'fedavgM' or 'fedprox'
  model_name: 'cnn-mnist'  # 'mnist-mlp' or 'cnn-mnist'
