dirichlet:
  alpha: 0.5  # alpha for dirichlet distribution

client:
  num_clients: 30  # number of clients
  epochs: 5  # number of epochs
  lr: 0.01  # learning rate

global:
  rounds: 100  # number of rounds

dataset:
  distribution: 'dirichlet'  # 'iid' or 'dirichlet'
  name: 'mnist'  # 'mnist' or 'cifar10'
  path: 'dataset/'  # path to dataset
  num_classes: 10  # number of classes in dataset
  batch_size: 64  # batch size

train:
  momentum: 0.9  # momentum for aggregation
  model_name: 'cnn-mnist'  # 'mnist-mlp' or 'cnn-mnist'
